
name: QuietWire CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Run Linting
      run: |
        echo "Running lint checks..."
        flake8 . || true

    - name: Run Tests
      run: |
        echo "Running unit tests..."
        pytest || true

    - name: Security Scan
      uses: anchore/scan-action@v3
      with:
        path: "."
      continue-on-error: true

    - name: Export Evidence
      run: |
        mkdir -p evidence
        echo "Build Timestamp: $(date)" > evidence/ci_log.txt
        echo "Commit: $GITHUB_SHA" >> evidence/ci_log.txt
        echo "Branch: $GITHUB_REF" >> evidence/ci_log.txt
        echo "Evidence exported."

    - name: Upload Evidence Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ci-evidence
        path: evidence/
