
markdown-lint.yml

name: Markdown Quality Check

on:
  pull_request:
    paths:
      - "**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1


---
